---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - exiftool
      - golang-go
      - feroxbuster
      - neo4j
      - rsyslog
      - ufw
      - dconf-cli
      - cargo
      - wine
      - bloodhound
      - python3-wsgidav
      - keepass2
      - gobuster
      - oscanner
      - sipvicious
      - tnscmd10g
      - wkhtmltopdf
      - snmp-mibs-downloader
    state: latest
  become: true
  become_method: sudo
